{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.metadata.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: {{ .Values.metadata.namespace }}
spec:
  rules:
  - host: jenkins.local.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ .Release.Name }}-{{ .Values.metadata.name }}-nodeport
              port: 
                number: {{ .Values.services.ingressPort }}

{{- end }}