kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-jenkins
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi