apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.metadata.name }}-nodeport
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.metadata.label }}
  ports:
    - protocol: {{ .Values.services.protocol }}
      port: {{ .Values.services.port }}
      targetPort: {{ .Values.services.port }}
      nodePort: {{ .Values.services.nodePort }}
      name: http
