apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.metadata.name }}-agent-discovery
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: {{ .Values.metadata.label }}
  ports:
    - protocol: {{ .Values.services.protocol }}
      port: {{ .Values.services.agentPort }}
      targetPort: {{ .Values.services.agentPort }}
