{{- range .Values.jenkinsSlaves }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-{{ .name }}
  namespace: jenkins
  labels:
    app: jenkins-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-{{ .name }}
  template:
    metadata:
      labels:
        app: jenkins-{{ .name }}
    spec:
      serviceAccountName: jenkins-deployer
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: jenkins-{{ .name }}
        image: {{ .image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
{{- end }}
