{{- range .Values.jenkinsSlaves }}
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-{{ .name }}-svc
  namespace: jenkins
spec:
  selector:
    app: jenkins-{{ .name }}
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
{{- end }}